on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep files
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infrastructure/finalmain.bicep
        parameters: 'dataFactoryName=biceptemplateadfexrg storageSKU=Standard_LRS storageAccountName=bicepstaccountexrg deployStorage=true deployADF=true projectName=bicepeventhub deployEventHub=true'
        failOnStdErr: false
